server.port: 9000
spring:

  cloud:
    gateway:
      routes:
      - id: Booking
        uri: http://localhost:8082/
        predicates:
        - Path=/user/**
        
      - id: FlightDetails
        uri: http://localhost:8081/
        predicates:
        - Path=/admin/**
     
     
      - id: Payment
        uri: http://localhost:8083/
        predicates:
        - Path=/pay/**

      - id: Search
        uri: http://localhost:8084/
        predicates:
        - Path=/user/**
        
      - id: Checkin
        uri: http://localhost:8086/
        predicates:
        - Path=/checkIn/**
        
            
